-- MySQL Script generated by MySQL Workbench
-- 06/14/17 11:53:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_vs-oade
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_vs-oade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_vs-oade` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_vs-oade` ;

-- -----------------------------------------------------
-- Table `db_vs-oade`.`town`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vs-oade`.`town` (
  `idTown` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `password` VARCHAR(45) NULL,
  `electedPassword` VARCHAR(45) NULL,
  `adminPassword` VARCHAR(45) NULL,
  PRIMARY KEY (`idTown`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vs-oade`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vs-oade`.`project` (
  `idProject` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(400) NULL,
  `poLastname` VARCHAR(45) NULL,
  `poFirstname` VARCHAR(45) NULL,
  `town_idTown` INT NOT NULL,
  PRIMARY KEY (`idProject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vs-oade`.`survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vs-oade`.`survey` (
  `idSurvey` INT NOT NULL AUTO_INCREMENT,
  `questionId` VARCHAR(10) NULL,
  `answer` VARCHAR(400) NULL,
  `grade1` INT NULL,
  `grade2` INT NULL,
  `openQuestion` VARCHAR(400) NULL,
  `comment` VARCHAR(400) NULL,
  `project_idProject` INT NOT NULL,
  PRIMARY KEY (`idSurvey`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db_vs-oade`.`archive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vs-oade`.`archive` (
  `idArchive` INT NOT NULL AUTO_INCREMENT,
  `townName` VARCHAR(100) NULL,
  `projectName` VARCHAR(45) NULL,
  `projectDescription` VARCHAR(400) NULL,
  `projectPoLastname` VARCHAR(45) NULL,
  `projectPoFirstname` VARCHAR(45) NULL,
  `questionId` VARCHAR(10) NULL,
  `answer` VARCHAR(400) NULL,
  `grade1` INT NULL,
  `grade2` INT NULL,
  `openQuestion` VARCHAR(400) NULL,
  `comment` VARCHAR(400) NULL,
  `projectId` INT NOT NULL,
  `townId` INT NOT NULL,
  `question` VARCHAR(400) NOT NULL,
  `questionComment` VARCHAR(400) NULL,
  PRIMARY KEY (`idArchive`))
ENGINE = InnoDB;


/*SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;*/

INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Agarn', 'Agarn', 'Agarn', 'Agarn');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Albinen', 'Albinen', 'Albinen', 'Albinen');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Anniviers', 'Anniviers', 'Anniviers', 'Anniviers');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Arbaz', 'Arbaz', 'Arbaz', 'Arbaz');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Ardon', 'Ardon', 'Ardon', 'Ardon');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Ausserberg', 'Ausserberg', 'Ausserberg', 'Ausserberg');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Ayent', 'Ayent', 'Ayent', 'Ayent');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Bagnes', 'Bagnes', 'Bagnes', 'Bagnes');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Baltschieder', 'Baltschieder', 'Baltschieder', 'Baltschieder');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Bellwald', 'Bellwald', 'Bellwald', 'Bellwald');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Bettmeralp', 'Bettmeralp', 'Bettmeralp', 'Bettmeralp');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Binn', 'Binn', 'Binn', 'Binn');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Bister', 'Bister', 'Bister', 'Bister');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Bitsch', 'Bitsch', 'Bitsch', 'Bitsch');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Blatten', 'Blatten', 'Blatten', 'Blatten');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Bourg-Saint-Pierre', 'Bourg-Saint-Pierre', 'Bourg-Saint-Pierre', 'Bourg-Saint-Pierre');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Bovernier', 'Bovernier', 'Bovernier', 'Bovernier');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Brigue-Glis', 'Brigue-Glis', 'Brigue-Glis', 'Brigue-Glis');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Bürchen', 'Bürchen', 'Bürchen', 'Bürchen');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Chalais', 'Chalais', 'Chalais', 'Chalais');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Chamoson', 'Chamoson', 'Chamoson', 'Chamoson');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Champéry', 'Champéry', 'Champéry', 'Champéry');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Charrat', 'Charrat', 'Charrat', 'Charrat');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Chippis', 'Chippis', 'Chippis', 'Chippis');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Collombey-Murraz', 'Collombey-Murraz', 'Collombey-Murraz', 'Collombey-Murraz');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Collonges', 'Collonges', 'Collonges', 'Collonges');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Conthey', 'Conthey', 'Conthey', 'Conthey');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Crans-Montana', 'Crans-Montana', 'Crans-Montana', 'Crans-Montana');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Dorénaz', 'Dorénaz', 'Dorénaz', 'Dorénaz');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Eggerberg', 'Eggerberg', 'Eggerberg', 'Eggerberg');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Eischoll', 'Eischoll', 'Eischoll', 'Eischoll');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Eisten', 'Eisten', 'Eisten', 'Eisten');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Embd', 'Embd', 'Embd', 'Embd');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Ergisch', 'Ergisch', 'Ergisch', 'Ergisch');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Ernen', 'Ernen', 'Ernen', 'Ernen');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Evionnaz', 'Evionnaz', 'Evionnaz', 'Evionnaz');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Evolène', 'Evolène', 'Evolène', 'Evolène');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Ferden', 'Ferden', 'Ferden', 'Ferden');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Fiesch', 'Fiesch', 'Fiesch', 'Fiesch');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Fieschertal', 'Fieschertal', 'Fieschertal', 'Fieschertal');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Finhaut', 'Finhaut', 'Finhaut', 'Finhaut');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Fully', 'Fully', 'Fully', 'Fully');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Gampel-Bratsch', 'Gampel-Bratsch', 'Gampel-Bratsch', 'Gampel-Bratsch');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Goms', 'Goms', 'Goms', 'Goms');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Grächen', 'Grächen', 'Grächen', 'Grächen');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Grengiols', 'Grengiols', 'Grengiols', 'Grengiols');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Grimisuat', 'Grimisuat', 'Grimisuat', 'Grimisuat');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Grône', 'Grône', 'Grône', 'Grône');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Guttet-Feschel', 'Guttet-Feschel', 'Guttet-Feschel', 'Guttet-Feschel');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Hérémence', 'Hérémence', 'Hérémence', 'Hérémence');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Icogne', 'Icogne', 'Icogne', 'Icogne');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Inden', 'Inden', 'Inden', 'Inden');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Isérables', 'Isérables', 'Isérables', 'Isérables');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Kippel', 'Kippel', 'Kippel', 'Kippel');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Lalden', 'Lalden', 'Lalden', 'Lalden');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Lax', 'Lax', 'Lax', 'Lax');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Lens', 'Lens', 'Lens', 'Lens');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Leytron', 'Leytron', 'Leytron', 'Leytron');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Liddes', 'Liddes', 'Liddes', 'Liddes');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Loèche', 'Loèche', 'Loèche', 'Loèche');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Loèche-les-Bains', 'Loèche-les-Bains', 'Loèche-les-Bains', 'Loèche-les-Bains');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Martigny', 'Martigny', 'Martigny', 'Martigny');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Martigny-Combe', 'Martigny-Combe', 'Martigny-Combe', 'Martigny-Combe');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Massongex', 'Massongex', 'Massongex', 'Massongex');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Miège', 'Miège', 'Miège', 'Miège');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Mont-Noble', 'Mont-Noble', 'Mont-Noble', 'Mont-Noble');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Monthey', 'Monthey', 'Monthey', 'Monthey');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Mörel-Filet', 'Mörel-Filet', 'Mörel-Filet', 'Mörel-Filet');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Naters', 'Naters', 'Naters', 'Naters');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Nendaz', 'Nendaz', 'Nendaz', 'Nendaz');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Niedergesteln', 'Niedergesteln', 'Niedergesteln', 'Niedergesteln');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Oberems', 'Oberems', 'Oberems', 'Oberems');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Obergoms', 'Obergoms', 'Obergoms', 'Obergoms');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Orsières', 'Orsières', 'Orsières', 'Orsières');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Port-Valais', 'Port-Valais', 'Port-Valais', 'Port-Valais');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Randa', 'Randa', 'Randa', 'Randa');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Rarogne', 'Rarogne', 'Rarogne', 'Rarogne');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Riddes', 'Riddes', 'Riddes', 'Riddes');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Ried-Brig', 'Ried-Brig', 'Ried-Brig', 'Ried-Brig');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Riederalp', 'Riederalp', 'Riederalp', 'Riederalp');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Saas-Almagell', 'Saas-Almagell', 'Saas-Almagell', 'Saas-Almagell');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Saas-Balen', 'Saas-Balen', 'Saas-Balen', 'Saas-Balen');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Saas-Fee', 'Saas-Fee', 'Saas-Fee', 'Saas-Fee');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Saas-Grund', 'Saas-Grund', 'Saas-Grund', 'Saas-Grund');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Saillon', 'Saillon', 'Saillon', 'Saillon');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Saint-Gingolph', 'Saint-Gingolph', 'Saint-Gingolph', 'Saint-Gingolph');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Saint-Léonard', 'Saint-Léonard', 'Saint-Léonard', 'Saint-Léonard');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Saint-Martin', 'Saint-Martin', 'Saint-Martin', 'Saint-Martin');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Saint-Maurice', 'Saint-Maurice', 'Saint-Maurice', 'Saint-Maurice');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Saint-Nicolas', 'Saint-Nicolas', 'Saint-Nicolas', 'Saint-Nicolas');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Salquenen', 'Salquenen', 'Salquenen', 'Salquenen');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Salvan', 'Salvan', 'Salvan', 'Salvan');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Savièse', 'Savièse', 'Savièse', 'Savièse');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Saxon', 'Saxon', 'Saxon', 'Saxon');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Sembrancher', 'Sembrancher', 'Sembrancher', 'Sembrancher');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Sierre', 'Sierre', 'Sierre', 'Sierre');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Simplon', 'Simplon', 'Simplon', 'Simplon');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Sion', 'Sion', 'Sion', 'Sion');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Stalden', 'Stalden', 'Stalden', 'Stalden');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Staldenried', 'Staldenried', 'Staldenried', 'Staldenried');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Steg-Hohtenn', 'Steg-Hohtenn', 'Steg-Hohtenn', 'Steg-Hohtenn');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Täsch', 'Täsch', 'Täsch', 'Täsch');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Termen', 'Termen', 'Termen', 'Termen');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Törbel', 'Törbel', 'Törbel', 'Törbel');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Turtmann-Unterems', 'Turtmann-Unterems', 'Turtmann-Unterems', 'Turtmann-Unterems');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Trient', 'Trient', 'Trient', 'Trient');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Troistorrents', 'Troistorrents', 'Troistorrents', 'Troistorrents');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Unterbäch', 'Unterbäch', 'Unterbäch', 'Unterbäch');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Val-d\'Illiez', 'Val-d\'Illiez', 'Val-d\'Illiez', 'Val-d\'Illiez');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Varonne', 'Varonne', 'Varonne', 'Varonne');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Venthône', 'Venthône', 'Venthône', 'Venthône');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Vernayaz', 'Vernayaz', 'Vernayaz', 'Vernayaz');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Vérossaz', 'Vérossaz', 'Vérossaz', 'Vérossaz');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Vétroz', 'Vétroz', 'Vétroz', 'Vétroz');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Vex', 'Vex', 'Vex', 'Vex');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Veyras', 'Veyras', 'Veyras', 'Veyras');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Veysonnaz', 'Veysonnaz', 'Veysonnaz', 'Veysonnaz');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Viège', 'Viège', 'Viège', 'Viège');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Vionnaz', 'Vionnaz', 'Vionnaz', 'Vionnaz');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Visperterminen', 'Visperterminen', 'Visperterminen', 'Visperterminen');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Vollèges', 'Vollèges', 'Vollèges', 'Vollèges');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Vouvry', 'Vouvry', 'Vouvry', 'Vouvry');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Wiler', 'Wiler', 'Wiler', 'Wiler');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Zeneggen', 'Zeneggen', 'Zeneggen', 'Zeneggen');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Zermatt', 'Zermatt', 'Zermatt', 'Zermatt');
INSERT INTO `town`(`name`, `password`, `electedPassword`, `adminPassword`) VALUES ('Zwischbergen', 'Zwischbergen', 'Zwischbergen', 'Zwischbergen');